name: v2openwrt
on:
  workflow_dispatch:
  push:
    paths:
      - 'update.txt'
jobs:
  job1:
    uses: ./.github/workflows/share.yml
    secrets: 
      # CUSTOM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      # ZEROTIER_TOKEN: ${{ secrets.ZEROTIER_TOKEN }}
      # WX_PUSH_APP_TOKEN: ${{ secrets.WX_PUSH_APP_TOKEN }}
      # WX_UID: ${{ secrets.WX_UID }}
      CYM_TOKEN: ${{ secrets.CYM_TOKEN }}
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
      REMOTE_PORT_V2: ${{ secrets.REMOTE_PORT_V2 }}
      LOCAL_PORT_O: ${{ secrets.LOCAL_PORT_O }}
      LOCAL_PORT_N: ${{ secrets.LOCAL_PORT_N }}
      USER: ${{ secrets.USER }}
      EMAIL: ${{ secrets.EMAIL }}
